// Source : https://leetcode-cn.com/problems/find-the-difference/
// Author ：GuoQiang Yao
// Date : 2021-11-10


/**************************************************************************************
You are given two strings s and t.String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1

**************************************************************************************/

/*******************************************************************************************************
题目分析： 小编采用的方法是从s串中一次遍历，将t串中的对应字符置以特殊标记。然后找出t串中没有特殊标记的字符即为所求
********************************************************************************************************/
class Solution {
public:
    char findTheDifference(string s, string t) {
        for(int i = 0;i < s.size(); ++i)
        {
            //从s串遍历，将t串中对应的字符置特殊标记
            int index = t.find(s[i]);
            t[index] = '0';
        }
        char a;
        //遍历t串，找出没有特殊标记的字符即为新添加的字符
        for(char ch:t)
            if(ch - 'a' >= 0)
                a = ch;
        return a;
    }
};
